In [1]:
#ライブラリ読み込み
import pandas as pd
import numpy as np
import optuna


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#統計＆土地利用データ読み込み
df = pd.read_csv("~/Desktop/趣味/CS2020_with_landuse_features.csv")

data = df.copy()

print(data.head())
print(data.shape)
print(data.columns)

        地域  TFR2022  R2020_log10(10万人あたり人口密度)  J2020労働力人口女性割合  \
0  北海道 札幌市     1.09                  3.652768        0.471028
1  北海道 函館市     1.18                  3.308714        0.470285
2  北海道 小樽市     1.12                  3.142921        0.475134
3  北海道 旭川市     1.29                  2.971137        0.466380
4  北海道 室蘭市     1.38                  3.278342        0.414711

   J2020第1次産業就業者比率【％】  T2020徒歩だけ  T2020鉄道・電車  T2020乗合バス  T2020勤め先・学校のバス  \
0                0.47   0.111804    0.215397   0.048770        0.006697
1                2.93   0.117959    0.020574   0.042005        0.009784
2                1.38   0.160906    0.062674   0.174740        0.010851
3                2.57   0.087152    0.005573   0.055984        0.010804
4                0.93   0.153458    0.011764   0.064882        0.022295

   T2020自家用車  ...  森林_ratio_valid  荒地_ratio_valid  建物用地_ratio_valid  \
0   0.351186  ...        0.665860        0.027077          0.188809
1   0.633064  ...        0.832173        0.019015          0.073001
2   0.468862  ...        0.765745        0.037571          0.105965
3   0.659623  ...        0.586615        0.014077          0.096088
4   0.663495  ...        0.477144        0.037750          0.267334

   道路_ratio_valid  鉄道_ratio_valid  その他用地_ratio_valid  河川湖沼_ratio_valid  \
0        0.015402        0.003091           0.044752          0.021985
1        0.004246        0.001561           0.018422          0.003841
2        0.011579        0.003582           0.036571          0.004582
3        0.007610        0.002342           0.024242          0.032837
4        0.016179        0.008731           0.123267          0.003852

   海浜_ratio_valid  海水域_ratio_valid  ゴルフ場_ratio_valid
0        0.000000         0.000000          0.004801
1        0.000500         0.002716          0.002997
2        0.002249         0.004082          0.006165
3        0.000000         0.000000          0.001969
4        0.001541         0.008988          0.006420

[5 rows x 57 columns]
(1728, 57)
Index(['地域', 'TFR2022', 'R2020_log10(10万人あたり人口密度)', 'J2020労働力人口女性割合',
       'J2020第1次産業就業者比率【％】', 'T2020徒歩だけ', 'T2020鉄道・電車', 'T2020乗合バス',
       'T2020勤め先・学校のバス', 'T2020自家用車', 'T2020利用交通手段が2種類', 'T2020利用交通手段が3種類以上',
       'T2020オートバイ', 'T2020自転車', 'T2020ハイヤー・タクシー', 'T2020その他',
       'P2020_log10(外国人人口（人口10万人当たり）)', 'P2020転入超過率（日本人移動者）【％】',
       'E2020_完全失業率【％】', '中卒女rate2020', '高校卒女ate2020', '短大高専卒女rate2020',
       '大学卒女rate2020', '大学院女rate2020', 'S2021_従業者数（民営）（農林漁業）',
       'S2021_従業者数（民営）（鉱業、採石業、砂利採取業）', 'S2021_従業者数（民営）（建設業）',
       'S2021_従業者数（民営）（製造業）', 'S2021_従業者数（民営）（電気・ガス・熱供給・水道業）【人】',
       'S2021_従業者数（民営）（情報通信業）', 'S2021_従業者数（民営）（運輸業、郵便業）',
       'S2021_従業者数（民営）（卸売業、小売業', 'S2021_従業者数（民営）（卸売業）', 'S2021従業者数（民営）（小売業）',
       'S2021_従業者数（民営）（金融業、保険業）', 'S2021_従業者数（民営）（不動産業、物品賃貸業）',
       'S2021_従業者数（民営）（学術研究、専門・技術サービス業）', 'S2021_従業者数（民営）（宿泊業、飲食サービス業）',
       'S2021_従業者数（民営）（生活関連サービス業、娯楽業', 'S2021_従業者数（民営）（教育、学習支援業）',
       'S2021従業者数（民営）（医療、福祉）', 'S2021_従業者数（民営）（複合サービス事業）',
       'S2021_従業者数（民営）（サービス業（他に分類されないもの））', 'code_5digit', 'city_code',
       '田_ratio_valid', 'その他農用地_ratio_valid', '森林_ratio_valid',
       '荒地_ratio_valid', '建物用地_ratio_valid', '道路_ratio_valid',
       '鉄道_ratio_valid', 'その他用地_ratio_valid', '河川湖沼_ratio_valid',
       '海浜_ratio_valid', '海水域_ratio_valid', 'ゴルフ場_ratio_valid'],
      dtype='str')

In [3]:
#観光データ読み込み
tourism = pd.read_csv(
    "~/Desktop/趣味/city2022.csv",
    encoding="cp932"
)

print(tourism.head())
print(tourism.shape)
print(tourism.columns.tolist())

      年  月  地域区分   データ区分  都道府県コード 都道府県名  地域コード    地域名称      人数
0  2022  1  市区町村  観光来訪者数        1   北海道   1101  札幌市中央区  230903
1  2022  1  市区町村  観光来訪者数        1   北海道   1102   札幌市北区   12000
2  2022  1  市区町村  観光来訪者数        1   北海道   1103   札幌市東区   22333
3  2022  1  市区町村  観光来訪者数        1   北海道   1104  札幌市白石区    5575
4  2022  1  市区町村  観光来訪者数        1   北海道   1105  札幌市豊平区   22257
(22392, 9)
['年', '月', '地域区分', 'データ区分', '都道府県コード', '都道府県名', '地域コード', '地域名称', '人数']

In [4]:
#市を区にまとめる
def aggregate_city_name(name):
    # 例：札幌市中央区 → 札幌市
    # 例：横浜市中区 → 横浜市
    # 例：大阪市北区 → 大阪市
    if "市" in name and name.endswith("区"):
        return name.split("市")[0] + "市"
    else:
        return name

tourism["地域名称_集約"] = tourism["地域名称"].apply(aggregate_city_name)

tourism[["都道府県名", "地域名称", "地域名称_集約"]].head(20)

   都道府県名    地域名称 地域名称_集約
0    北海道  札幌市中央区     札幌市
1    北海道   札幌市北区     札幌市
2    北海道   札幌市東区     札幌市
3    北海道  札幌市白石区     札幌市
4    北海道  札幌市豊平区     札幌市
5    北海道   札幌市南区     札幌市
6    北海道   札幌市西区     札幌市
7    北海道  札幌市厚別区     札幌市
8    北海道  札幌市手稲区     札幌市
9    北海道  札幌市清田区     札幌市
10   北海道     函館市     函館市
11   北海道     小樽市     小樽市
12   北海道     旭川市     旭川市
13   北海道     室蘭市     室蘭市
14   北海道     釧路市     釧路市
15   北海道     帯広市     帯広市
16   北海道     北見市     北見市
17   北海道     夕張市     夕張市
18   北海道    岩見沢市    岩見沢市
19   北海道     網走市     網走市

In [5]:
#年間観光来訪者数を作る
tourism_year = tourism.groupby(
    ["都道府県名", "地域名称_集約"],
    as_index=False
)["人数"].sum()

tourism_year = tourism_year.rename(columns={
    "人数": "年間観光来訪者数"
})

tourism_year["地域"] = tourism_year["都道府県名"] + " " + tourism_year["地域名称_集約"]

tourism_year = tourism_year[["地域", "年間観光来訪者数"]]

print(tourism_year.head())
print(tourism_year.shape)

         地域  年間観光来訪者数
0  三重県 いなべ市    714717
1   三重県 亀山市   1098992
2   三重県 伊勢市   5486040
3   三重県 伊賀市   2210262
4  三重県 南伊勢町     44059
(1731, 2)

In [6]:
#元データと観光データを結合
drop_cols = [
    col for col in data.columns
    if "年間観光来訪者数" in col
    or "観光人気度" in col
    or "log_年間観光来訪者数" in col
]

data = data.drop(columns=drop_cols, errors="ignore")

# 観光データを結合
data = data.merge(
    tourism_year,
    on="地域",
    how="left"
)

# 欠損を0にする
data["年間観光来訪者数"] = data["年間観光来訪者数"].fillna(0)

print(data[["地域", "年間観光来訪者数"]].head())
print("欠損数:", data["年間観光来訪者数"].isna().sum())
print(data.shape)

        地域   年間観光来訪者数
0  北海道 札幌市  9513626.0
1  北海道 函館市  1423538.0
2  北海道 小樽市  1129466.0
3  北海道 旭川市  2339891.0
4  北海道 室蘭市   284144.0
欠損数: 0
(1728, 58)

In [7]:
#観光人気度を作る
def minmax(s):
    if s.max() == s.min():
        return s * 0
    return (s - s.min()) / (s.max() - s.min())

# 観光客数は大きいためlog10をとる
data["log_年間観光来訪者数"] = np.log10(data["年間観光来訪者数"] + 1)

# 0〜100点にする
data["観光人気度"] = minmax(data["log_年間観光来訪者数"]) * 100

data[["地域", "年間観光来訪者数", "log_年間観光来訪者数", "観光人気度"]].sort_values(
    "年間観光来訪者数",
    ascending=False
).head(20)

            地域    年間観光来訪者数  log_年間観光来訪者数       観光人気度
973   愛知県 名古屋市  55145992.0      7.741514  100.000000
1101   大阪府 大阪市  34146093.0      7.533341   97.310953
616   東京都 千代田区  30760962.0      7.488000   96.725265
1075   京都府 京都市  27879311.0      7.445282   96.173463
618     東京都 港区  22475451.0      7.351708   94.964738
619    東京都 新宿区  22221546.0      7.346774   94.901002
631    東京都 豊島区  21668902.0      7.335837   94.759720
628    東京都 渋谷区  19852443.0      7.297814   94.268563
617    東京都 中央区  19206377.0      7.283445   94.082960
678   神奈川県 横浜市  19015393.0      7.279105   94.026897
623    東京都 江東区  16379234.0      7.214294   93.189700
621    東京都 台東区  15404536.0      7.187649   92.845517
939    静岡県 浜松市  14682049.0      7.166787   92.576035
1455   福岡県 福岡市  13623766.0      7.134297   92.156357
1144   兵庫県 神戸市  13528102.0      7.131237   92.116825
679   神奈川県 川崎市  11855845.0      7.073933   91.376604
586    千葉県 浦安市  11850238.0      7.073727   91.373950
938    静岡県 静岡市  11797715.0      7.071798   91.349030
951   静岡県 御殿場市  10405305.0      7.017255   90.644477
620    東京都 文京区   9696371.0      6.986609   90.248617

In [8]:
#旅行向けスコアの作成
# =========================
# 基本特徴量
# =========================

pop_density = data["R2020_log10(10万人あたり人口密度)"]

building = data["建物用地_ratio_valid"]
road = data["道路_ratio_valid"]
rail_land = data["鉄道_ratio_valid"]

forest = data["森林_ratio_valid"]
rice = data["田_ratio_valid"]
farm = data["その他農用地_ratio_valid"]
river = data["河川湖沼_ratio_valid"]
beach = data["海浜_ratio_valid"]
sea = data["海水域_ratio_valid"]

walk = data["T2020徒歩だけ"]
train = data["T2020鉄道・電車"]
car = data["T2020自家用車"]

primary = data["J2020第1次産業就業者比率【％】"]

hotel_food = data["S2021_従業者数（民営）（宿泊業、飲食サービス業）"]
retail = data["S2021従業者数（民営）（小売業）"]
entertainment = data["S2021_従業者数（民営）（生活関連サービス業、娯楽業"]

In [9]:
#各スコアの作成
# =========================
# 旅行向けスコア
# =========================

data["都会度"] = (
    0.35 * minmax(pop_density)
    + 0.30 * minmax(building)
    + 0.15 * minmax(road)
    + 0.20 * minmax(train)
) * 100

data["自然度"] = (
    0.45 * minmax(forest)
    + 0.25 * minmax(rice + farm)
    + 0.15 * minmax(river)
    + 0.15 * (1 - minmax(building))
) * 100

data["海度"] = (
    0.70 * minmax(sea)
    + 0.30 * minmax(beach)
) * 100

data["山っぽさ"] = (
    0.70 * minmax(forest)
    + 0.20 * (1 - minmax(building))
    + 0.10 * (1 - minmax(pop_density))
) * 100

data["田舎度"] = (
    0.30 * minmax(forest)
    + 0.25 * minmax(rice + farm)
    + 0.20 * minmax(car)
    + 0.15 * minmax(primary)
    + 0.10 * (1 - minmax(pop_density))
) * 100

data["電車旅向き"] = (
    0.55 * minmax(train)
    + 0.20 * minmax(rail_land)
    + 0.15 * minmax(walk)
    + 0.10 * minmax(pop_density)
) * 100

data["車旅向き"] = (
    0.55 * minmax(car)
    + 0.20 * minmax(road)
    + 0.15 * (1 - minmax(train))
    + 0.10 * (1 - minmax(pop_density))
) * 100

data["観光・街歩き向き"] = (
    0.30 * minmax(hotel_food)
    + 0.25 * minmax(retail)
    + 0.20 * minmax(entertainment)
    + 0.15 * minmax(walk)
    + 0.10 * minmax(train)
) * 100

data["観光地らしさ"] = (
    0.25 * data["観光人気度"] / 100
    + 0.20 * data["海度"] / 100
    + 0.20 * data["山っぽさ"] / 100
    + 0.15 * data["自然度"] / 100
    + 0.10 * minmax(hotel_food)
    + 0.05 * minmax(entertainment)
    + 0.05 * minmax(retail)
) * 100

In [10]:
#確認
score_cols = [
    "都会度", "自然度", "海度", "山っぽさ", "田舎度",
    "電車旅向き", "車旅向き", "観光・街歩き向き",
    "観光人気度", "観光地らしさ"
]

data[["地域", "年間観光来訪者数"] + score_cols].head()

,地域,年間観光来訪者数,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き,観光人気度,観光地らしさ
0,北海道 札幌市,9513626.0,41.894755,43.859379,0.000000,65.357749,30.861230,30.530268,34.232558,19.059049,90.141879,45.248454
1,北海道 函館市,1423538.0,27.445808,53.257512,2.753736,80.739575,44.343092,12.390420,56.563040,19.077981,79.485349,48.366943
2,北海道 小樽市,1129466.0,28.739773,49.095775,5.045545,75.782821,38.111970,17.302367,46.428972,19.714833,78.187207,46.461454
3,北海道 旭川市,2339891.0,24.504167,48.408605,0.000000,63.762719,44.328090,9.260559,59.962465,15.762068,82.273259,43.754160
4,北海道 室蘭市,284144.0,34.186023,34.056736,9.043601,51.321299,34.136245,13.975297,60.070615,15.963786,70.445394,37.500902

In [11]:
data[["地域", "年間観光来訪者数", "観光人気度", "観光地らしさ", "海度", "山っぽさ", "自然度"]].sort_values(
    "観光地らしさ",
    ascending=False
).head(30)

,地域,年間観光来訪者数,観光人気度,観光地らしさ,海度,山っぽさ,自然度
1715,沖縄県 座間味村,41262.0,59.620906,61.748664,71.305906,79.023367,49.765015
677,東京都 小笠原村,19832.0,55.510956,57.676919,70.000000,83.506251,50.906998
1714,沖縄県 渡嘉敷村,13777.0,53.467399,56.893471,55.798309,81.379837,51.460065
1036,三重県 鳥羽市,2248085.0,82.048718,55.671335,15.983673,82.447658,53.757524
367,福島県 北塩原村,721386.0,75.672127,55.385531,0.000000,89.456370,57.945382
706,神奈川県 箱根町,3843379.0,85.057178,54.051054,0.000000,76.250200,50.376346
736,新潟県 湯沢町,1772521.0,80.715370,53.955837,0.000000,91.072575,57.137636
1725,沖縄県 竹富町,185241.0,68.045340,53.818213,12.300055,87.096550,56.529033
364,福島県 檜枝岐村,68025.0,62.425450,53.790119,0.000000,98.135321,59.268207
489,群馬県 片品村,1403726.0,79.406724,53.487526,0.000000,91.767012,57.965313
885,長野県 小谷村,801215.0,76.260918,53.251493,0.000000,91.355490,57.280076
889,長野県 山ノ内町,1179530.0,78.430516,53.116457,0.000000,87.292583,56.827350
1244,和歌山県 白浜町,3074098.0,83.804252,53.059198,6.546171,82.541597,54.391307
1702,沖縄県 恩納村,609042.0,74.722438,52.834443,17.202009,71.994160,49.173624
1554,長崎県 新上五島町,371401.0,71.947739,52.789766,25.083758,88.052145,56.022858
862,長野県 平谷村,209365.0,68.732113,52.754992,0.000000,94.517594,59.287071
937,岐阜県 白川村,515797.0,73.790213,52.686927,0.000000,96.009537,58.818276
492,群馬県 みなかみ町,2865049.0,83.409166,52.666904,0.000000,89.672830,56.884255
891,長野県 野沢温泉村,526863.0,73.909297,52.513469,0.000000,82.742595,55.019392
844,長野県 軽井沢町,4464191.0,85.897189,52.355092,0.000000,75.085272,48.630893
1251,和歌山県 串本町,714117.0,75.615313,52.223613,17.695634,84.356922,54.555990
956,静岡県 伊豆市,2591407.0,82.846015,52.188755,0.740681,86.790913,56.416364
1260,鳥取県 三朝町,792645.0,76.200589,52.109279,0.000000,91.470854,58.813672
1677,鹿児島県 瀬戸内町,145054.0,66.673428,51.864194,23.790175,90.885203,57.449489
884,長野県 白馬村,1571096.0,80.038647,51.859473,0.000000,81.249225,52.195215
1355,山口県 上関町,172695.0,67.651913,51.858132,36.142586,83.908547,54.842662
1697,沖縄県 国頭村,305497.0,70.851882,51.808034,7.270877,90.445862,58.036857
898,岐阜県 高山市,2711955.0,83.101092,51.777681,0.000000,90.892143,58.358761
1215,奈良県 天川村,121695.0,65.688395,51.776557,0.000000,94.313504,59.345615
57,北海道 ニセコ町,845794.0,76.564676,51.710215,0.000000,79.885307,54.241641

In [12]:


# 目的変数
y = data["log_年間観光来訪者数"]

# 説明変数
feature_cols = [
    "都会度",
    "自然度",
    "海度",
    "山っぽさ",
    "田舎度",
    "電車旅向き",
    "車旅向き",
    "観光・街歩き向き",
    "R2020_log10(10万人あたり人口密度)",
    "建物用地_ratio_valid",
    "道路_ratio_valid",
    "鉄道_ratio_valid",
    "森林_ratio_valid",
    "田_ratio_valid",
    "その他農用地_ratio_valid",
    "河川湖沼_ratio_valid",
    "海浜_ratio_valid",
    "海水域_ratio_valid",
    "S2021_従業者数（民営）（宿泊業、飲食サービス業）",
    "S2021従業者数（民営）（小売業）",
    "S2021_従業者数（民営）（生活関連サービス業、娯楽業"
]

X = data[feature_cols]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (1382, 21)
X_test: (346, 21)
y_train: (1382,)
y_test: (346,)

In [13]:


def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
        "max_depth": trial.suggest_int("max_depth", 3, 30),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 10),
        "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),
        "random_state": 42,
        "n_jobs": -1
    }

    model = RandomForestRegressor(**params)

    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    scores = cross_val_score(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring="neg_root_mean_squared_error",
        n_jobs=-1
    )

    return -scores.mean()

In [14]:
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=30)

print("Best CV RMSE:", study.best_value)
print("Best params:")
print(study.best_params)

[I 2026-07-01 19:24:30,869] A new study created in memory with name: no-name-2ad4ce0d-8c39-46ac-9d5d-bf301486b093
[I 2026-07-01 19:24:38,987] Trial 0 finished with value: 0.7670723738781129 and parameters: {'n_estimators': 776, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 0.7670723738781129.
[I 2026-07-01 19:24:44,518] Trial 1 finished with value: 0.7607151928270632 and parameters: {'n_estimators': 775, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:24:50,204] Trial 2 finished with value: 0.7767959071957187 and parameters: {'n_estimators': 880, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:24:51,428] Trial 3 finished with value: 0.7695602042616521 and parameters: {'n_estimators': 275, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:24:54,034] Trial 4 finished with value: 0.7867941356218021 and parameters: {'n_estimators': 801, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:24:59,179] Trial 5 finished with value: 0.7778850622166893 and parameters: {'n_estimators': 496, 'max_depth': 8, 'min_samples_split': 20, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:25:02,573] Trial 6 finished with value: 0.7633054077182917 and parameters: {'n_estimators': 728, 'max_depth': 28, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:25:06,738] Trial 7 finished with value: 0.7631967801069448 and parameters: {'n_estimators': 985, 'max_depth': 16, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7607151928270632.
[I 2026-07-01 19:25:10,078] Trial 8 finished with value: 0.7840612437456551 and parameters: {'n_estimators': 965, 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 1 with value: 0.7607151928270632.
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/parallel.py:144: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(

Best CV RMSE: 0.7590113224610633
Best params:
{'n_estimators': 1000, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'log2'}

In [15]:
best_params = study.best_params

rf_best = RandomForestRegressor(
    **best_params,
    random_state=42,
    n_jobs=-1
)

rf_best.fit(X_train, y_train)

RandomForestRegressor(max_depth=15, max_features='log2', min_samples_leaf=2,
                      min_samples_split=4, n_estimators=1000, n_jobs=-1,
                      random_state=42)

In [16]:
y_pred_train = rf_best.predict(X_train)
y_pred_test = rf_best.predict(X_test)

r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = np.sqrt(mean_squared_error(y_test, y_pred_test))

print("Random Forest after Optuna")
print("Train R2:", r2_train)
print("Test R2:", r2_test)
print("Test MAE:", mae_test)
print("Test RMSE:", rmse_test)

Random Forest after Optuna
Train R2: 0.7944260164178781
Test R2: 0.3480322003783537
Test MAE: 0.492223526186729
Test RMSE: 0.7681515163048199

In [17]:
data["ML予測_log観光来訪者数"] = rf_best.predict(X)

data["ML観光ポテンシャル"] = minmax(data["ML予測_log観光来訪者数"]) * 100

In [18]:
data[[
    "地域",
    "年間観光来訪者数",
    "観光人気度",
    "ML観光ポテンシャル",
    "都会度",
    "自然度",
    "海度",
    "山っぽさ",
    "観光・街歩き向き"
]].sort_values(
    "ML観光ポテンシャル",
    ascending=False
).head(30)

,地域,年間観光来訪者数,観光人気度,ML観光ポテンシャル,都会度,自然度,海度,山っぽさ,観光・街歩き向き
1101,大阪府 大阪市,34146093.0,97.310953,100.000000,71.728679,7.458713,2.992677,6.648348,17.839619
619,東京都 新宿区,22221546.0,94.901002,99.668078,84.233339,3.252535,0.000000,4.507652,21.670196
621,東京都 台東区,15404536.0,92.845517,96.315077,83.081530,4.676194,0.000000,5.267706,22.729419
622,東京都 墨田区,6593963.0,88.085439,96.042541,82.729353,6.102775,0.000000,4.503391,22.871969
618,東京都 港区,22475451.0,94.964738,95.052661,77.523811,6.493295,4.412439,8.985566,17.663796
623,東京都 江東区,16379234.0,93.189700,95.032030,72.987731,9.508879,10.701955,10.337366,16.972958
1075,京都府 京都市,27879311.0,96.173463,94.636387,41.777446,48.200471,0.000000,71.552746,19.851625
679,神奈川県 川崎市,11855845.0,91.376604,94.629278,71.588598,8.106835,6.188044,9.628527,20.857473
678,神奈川県 横浜市,19015393.0,94.026897,93.735835,69.307319,10.434729,2.762077,13.113854,20.947089
620,東京都 文京区,9696371.0,90.248617,93.245302,85.245816,3.795310,0.000000,5.216957,19.380667
939,静岡県 浜松市,14682049.0,92.576035,92.822925,28.002015,49.661760,1.221359,69.486696,13.306054
626,東京都 大田区,5486787.0,87.054266,92.616914,71.265673,7.372069,7.801243,8.361875,19.593086
938,静岡県 静岡市,11797715.0,91.349030,92.478760,28.928802,52.696315,1.181212,76.893577,14.527526
586,千葉県 浦安市,11850238.0,91.373950,91.958478,68.609380,6.766621,11.919997,8.432870,29.555561
0,北海道 札幌市,9513626.0,90.141879,91.689974,41.894755,43.859379,0.000000,65.357749,19.059049
973,愛知県 名古屋市,55145992.0,100.000000,91.662490,65.279737,7.831478,1.476371,9.476066,16.822533
1455,福岡県 福岡市,13623766.0,92.156357,91.480949,50.530150,27.950725,7.008905,38.639406,17.250949
249,宮城県 仙台市,7326779.0,88.676623,91.341158,38.610603,43.556255,1.396813,62.105010,16.958247
624,東京都 品川区,4145769.0,85.482055,91.331228,80.128374,5.177418,5.007457,7.004974,18.933195
756,石川県 金沢市,5132416.0,86.679711,91.136566,32.051374,45.455262,1.188875,65.393223,14.654301
1317,広島県 広島市,6413203.0,87.929507,91.009662,36.836963,47.289148,0.771894,69.947472,15.953048
617,東京都 中央区,19206377.0,94.082960,90.845833,84.749800,8.872554,4.489272,8.200563,18.759845
631,東京都 豊島区,21668902.0,94.759720,90.357779,87.040325,1.256182,0.000000,1.714226,26.057621
616,東京都 千代田区,30760962.0,96.725265,90.328611,75.260121,14.759675,0.000000,20.337749,19.014794
1290,岡山県 岡山市,7071058.0,88.477325,89.912872,31.062352,42.924917,1.157356,54.549883,14.031290
1106,大阪府 吹田市,2552237.0,82.760571,88.736459,71.917950,8.250151,0.000000,12.035592,20.140541
1222,和歌山県 和歌山市,5500806.0,87.068582,88.493795,38.538692,32.300811,5.625934,39.735012,13.898602
1599,大分県 大分市,3092231.0,83.837246,88.345057,31.681797,42.354599,2.777384,59.221300,14.473595
1185,奈良県 奈良市,5857900.0,87.421428,88.177356,39.804591,42.301161,0.000000,59.077147,21.055111
1158,兵庫県 三木市,6586943.0,88.079464,88.008791,26.361949,43.680721,0.000000,56.464211,15.757012

In [19]:
data["観光ポテンシャル差"] = data["ML観光ポテンシャル"] - data["観光人気度"]

In [20]:
data[[
    "地域",
    "観光人気度",
    "ML観光ポテンシャル",
    "観光ポテンシャル差",
    "都会度",
    "自然度",
    "海度",
    "山っぽさ",
    "田舎度",
    "観光・街歩き向き"
]].sort_values(
    "観光ポテンシャル差",
    ascending=False
).head(30)

,地域,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,観光・街歩き向き
251,宮城県 塩竈市,0.000000,68.058153,68.058153,51.154719,16.086690,58.401762,25.094669,22.959432,16.829282
51,北海道 今金町,0.000000,62.206893,62.206893,6.753773,56.218200,0.000000,85.229302,55.788292,21.118370
123,北海道 訓子府町,0.000000,57.715861,57.715861,8.355039,52.096879,0.000000,63.379717,61.321630,11.662414
109,北海道 猿払村,0.000000,49.308559,49.308559,3.657830,51.951353,1.946474,80.009851,54.815359,9.974045
1117,大阪府 河内長野市,0.000000,34.508063,34.508063,38.069310,49.524705,0.000000,74.185791,36.006071,19.942288
401,茨城県 龍ケ崎市,0.000000,33.164819,33.164819,33.742727,32.803724,0.000000,26.287036,35.592322,17.410833
1288,島根県 知夫村,21.100116,53.899166,32.799050,14.687577,51.379401,26.958695,82.266521,48.506547,19.693587
588,千葉県 袖ケ浦市,0.000000,29.898211,29.898211,32.327999,32.923261,1.920391,35.117093,36.796225,11.283364
583,千葉県 鎌ケ谷市,0.000000,26.295818,26.295818,60.987430,13.012962,0.000000,12.019381,14.549123,24.103919
236,岩手県 金ケ崎町,0.000000,26.072396,26.072396,14.563535,50.296200,0.000000,62.016848,54.515972,6.782429
921,岐阜県 関ケ原町,0.000000,24.821699,24.821699,24.066458,53.640348,0.000000,81.214629,48.126566,10.691475
1707,沖縄県 嘉手納町,48.690441,71.986278,23.295836,28.231165,26.388662,0.000000,39.464415,30.145285,16.126970
1447,高知県 檮原町,0.000000,20.023806,20.023806,12.515639,59.291339,0.000000,93.584550,56.155792,17.786228
1488,福岡県 久山町,56.746178,74.360817,17.614638,24.393516,49.592679,0.000000,73.979865,44.437424,9.974477
71,北海道 上砂川町,0.000000,17.605082,17.605082,19.634925,56.401910,0.000000,89.325191,49.931860,9.767757
303,秋田県 八郎潟町,46.298671,63.858737,17.560065,23.101634,41.661651,0.000000,37.919771,47.050897,15.156465
1592,熊本県 湯前町,53.224002,69.715368,16.491365,16.835093,54.156411,0.000000,78.508040,57.853049,16.451733
599,千葉県 酒々井町,52.888444,67.348704,14.460260,41.170249,32.412798,0.000000,35.847110,32.608898,29.839149
68,北海道 古平町,0.000000,14.339482,14.339482,10.908806,58.809420,0.582596,93.911388,50.859426,14.905580
199,青森県 野辺地町,58.552910,71.878594,13.325683,20.473358,52.245816,2.483988,76.694931,48.343329,19.991233
45,北海道 長万部町,23.991851,37.280327,13.288475,9.235689,54.245869,4.417708,83.258568,52.396717,16.670844
1210,奈良県 河合町,51.142252,64.380589,13.238337,49.932156,21.871529,0.000000,21.571938,22.478881,24.704022
1331,広島県 府中町,55.140010,68.172857,13.032847,48.203245,30.092928,0.000000,45.462783,22.575526,16.084477
239,岩手県 大槌町,57.608685,70.349520,12.740835,18.209908,58.207801,1.331065,90.474343,53.251162,16.875075
1083,京都府 向日市,55.916283,68.533853,12.617570,62.487483,13.761728,0.000000,16.645360,12.295885,21.360344
322,山形県 山辺町,57.436161,69.998198,12.562037,21.453972,50.322177,0.000000,65.659646,51.641757,15.498716
1332,広島県 海田町,52.006940,64.205285,12.198345,40.563826,38.876916,0.000000,58.497151,29.110715,16.855495
518,埼玉県 蕨市,61.680421,73.786098,12.105677,77.546174,0.259846,0.000000,0.994944,2.515007,24.163748
168,北海道 標茶町,51.049667,62.673050,11.623383,3.982009,50.048059,0.000000,67.501655,57.022229,21.195127
842,長野県 北相木村,0.000000,11.531709,11.531709,13.201221,59.446200,0.000000,92.924498,57.266492,14.980960

In [21]:
def recommend_area_ml(
    data,
    urban=0,
    nature=0,
    sea=0,
    mountain=0,
    rural=0,
    train_trip=0,
    car_trip=0,
    sightseeing=0,
    ml_tourism=0.5,
    top_n=10
):
    result = data.copy()

    total_weight = (
        urban + nature + sea + mountain + rural
        + train_trip + car_trip + sightseeing + ml_tourism
    )

    if total_weight == 0:
        raise ValueError("少なくとも1つの条件に重みを入れてください")

    result["おすすめスコア"] = (
        urban * result["都会度"]
        + nature * result["自然度"]
        + sea * result["海度"]
        + mountain * result["山っぽさ"]
        + rural * result["田舎度"]
        + train_trip * result["電車旅向き"]
        + car_trip * result["車旅向き"]
        + sightseeing * result["観光・街歩き向き"]
        + ml_tourism * result["ML観光ポテンシャル"]
    ) / total_weight

    display_cols = [
        "地域",
        "おすすめスコア",
        "観光人気度",
        "ML観光ポテンシャル",
        "観光ポテンシャル差",
        "都会度",
        "自然度",
        "海度",
        "山っぽさ",
        "田舎度",
        "電車旅向き",
        "車旅向き",
        "観光・街歩き向き"
    ]

    return result.sort_values("おすすめスコア", ascending=False)[display_cols].head(top_n)

In [22]:
recommend_area_ml(
    data,
    sea=1.0,
    nature=0.8,
    ml_tourism=0.6,
    top_n=20
)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
1715,沖縄県 座間味村,55.958239,59.620906,38.636424,-20.984483,15.646162,49.765015,71.305906,79.023367,34.783201,19.068919,35.183567,46.431111
677,東京都 小笠原村,53.561593,55.510956,29.703710,-25.807247,7.895623,50.906998,70.000000,83.506251,39.540315,14.819389,38.547114,32.110332
1714,沖縄県 渡嘉敷村,51.995438,53.467399,46.371149,-7.096251,16.956179,51.460065,55.798309,81.379837,40.513268,15.302928,47.738504,40.291104
1394,香川県 直島町,51.460717,67.364017,45.981705,-21.382312,22.905439,38.554626,65.072997,60.254601,31.486121,8.911615,45.414110,15.602115
1552,長崎県 小値賀町,51.059604,58.995489,48.841153,-10.154336,15.375095,45.923726,56.499377,61.463968,48.796648,9.301229,57.202855,25.468232
1717,沖縄県 渡名喜村,49.882809,37.500287,19.819627,-17.680660,16.044251,46.545180,70.590820,71.718261,36.971794,17.526315,38.631116,35.748825
1248,和歌山県 太地町,49.190147,70.299770,62.475672,-7.824097,27.819326,44.059684,45.323202,67.952244,43.599677,10.498559,64.026717,18.093428
1355,山口県 上関町,47.540241,67.651913,56.799773,-10.852140,14.532707,54.842662,36.142586,83.908547,51.706770,8.413006,61.832560,15.542171
1613,大分県 姫島村,46.754400,41.787991,42.734052,0.946061,20.069094,45.767200,49.956368,67.784787,37.126235,8.360846,38.719217,23.994002
251,宮城県 塩竈市,46.710836,0.000000,68.058153,68.058153,51.154719,16.086690,58.401762,25.094669,22.959432,25.183021,53.760720,16.829282
1411,愛媛県 上島町,46.139358,54.670969,46.877025,-7.793944,19.849816,47.298012,44.769835,62.442656,38.578599,9.447541,37.760819,13.811833
1554,長崎県 新上五島町,45.930509,71.947739,67.218629,-4.729110,18.078737,56.022858,25.083758,88.052145,51.445088,8.007830,65.462331,19.110419
428,茨城県 大洗町,45.835804,82.045700,82.294158,0.248459,29.711085,33.994164,33.434103,35.918497,37.647428,11.955601,64.274477,16.259979
1036,三重県 鳥羽市,44.639847,82.048718,80.243234,-1.805484,21.103392,53.757524,15.983673,82.447658,47.779130,12.470878,56.712844,29.347373
1286,島根県 海士町,44.589428,53.851730,51.021508,-2.830222,16.686147,53.509237,33.594332,82.613285,50.956442,8.605962,63.643947,16.608608
1720,沖縄県 伊平屋村,44.185724,49.791419,42.668484,-7.122935,12.192286,50.362620,40.154552,69.924662,55.182577,5.535354,71.718868,18.812190
1039,三重県 志摩市,44.177787,79.422205,76.696093,-2.726112,22.833948,48.670148,21.072914,72.399656,48.606163,9.224435,67.371190,21.977681
1251,和歌山県 串本町,44.003953,75.615313,73.781768,-1.833545,21.480280,54.555990,17.695634,84.356922,49.761061,10.036884,64.465718,21.858018
671,東京都 新島村,43.951925,50.240273,41.361351,-8.878922,16.608512,49.993837,40.672739,80.153941,44.663619,11.236348,59.991405,26.527449
1238,和歌山県 美浜町,43.885118,57.896778,54.020166,-3.876612,26.680061,43.661463,37.983012,58.865623,43.369942,9.401344,61.436149,13.119281

In [23]:
recommend_area_ml(
    data,
    mountain=1.0,
    nature=1.0,
    rural=0.5,
    ml_tourism=0.6,
    top_n=20
)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
914,岐阜県 郡上市,72.145425,84.332062,81.821013,-2.511049,17.426931,57.977010,0.000000,89.706491,53.749420,7.623474,70.102357,16.260495
489,群馬県 片品村,71.907456,79.406724,73.781537,-5.625187,11.963259,57.965313,0.000000,91.767012,57.823730,5.235531,71.588853,23.572944
492,群馬県 みなかみ町,71.853213,83.409166,81.549065,-1.860101,12.406199,56.884255,0.000000,89.672830,54.516874,8.979206,69.059534,22.370753
1048,三重県 大台町,71.733124,74.138708,76.774770,2.636062,17.342811,58.454599,0.000000,91.368575,52.969295,9.868467,66.505256,15.265492
895,長野県 栄村,71.712841,68.186314,63.301640,-4.884674,8.964725,59.123379,0.000000,94.549951,61.310986,7.797960,69.928061,18.092004
898,岐阜県 高山市,71.706554,83.101092,77.003661,-6.097431,16.202897,58.358761,0.000000,90.892143,53.674435,7.301005,66.880051,18.295927
217,岩手県 宮古市,71.629326,76.644527,74.756176,-1.888352,17.697850,58.905549,1.279312,92.007140,52.569036,8.430994,65.327241,16.744611
264,宮城県 七ヶ宿町,71.612384,69.486245,64.384990,-5.101255,6.686306,59.119069,0.000000,94.645609,59.205436,5.311687,71.120038,17.997724
912,岐阜県 飛騨市,71.600367,75.624363,73.751055,-1.873308,16.909548,58.873579,0.000000,91.784730,54.104392,7.636219,68.721806,12.468032
235,岩手県 西和賀町,71.592972,69.348399,66.376297,-2.972102,7.634018,58.958013,0.000000,93.281340,59.746163,4.722357,73.197012,16.249505
915,岐阜県 下呂市,71.534955,75.722110,75.690072,-0.032038,17.474017,58.597767,0.000000,91.317235,52.858631,9.993948,67.374588,18.900203
734,新潟県 阿賀町,71.506158,71.601973,68.907750,-2.694223,9.160395,58.268432,0.000000,93.710270,56.691476,6.498290,73.074548,15.300320
811,山梨県 道志村,71.451015,73.473327,68.848080,-4.625248,16.291589,59.462897,0.000000,92.786407,55.879992,6.843669,70.961659,17.785690
876,長野県 木曽町,71.436435,77.143042,75.308886,-1.834156,14.655834,58.286101,0.000000,91.374027,53.214979,10.346061,65.436236,20.629286
1260,鳥取県 三朝町,71.384855,76.200589,71.490038,-4.710551,14.705670,58.813672,0.000000,91.470854,56.229001,6.117094,71.127036,20.927134
1024,愛知県 設楽町,71.369539,74.696115,69.402300,-5.293815,13.175332,58.798837,0.000000,92.069993,57.470723,7.516591,70.089755,17.431787
1246,和歌山県 すさみ町,71.258325,75.394356,75.268202,-0.126154,16.665874,58.044319,3.923516,91.572946,52.245241,8.509334,63.481065,15.067004
861,長野県 阿智村,71.233466,72.874289,70.610596,-2.263693,15.587157,58.700255,0.000000,91.353170,56.807925,6.249103,72.283787,20.443786
1412,愛媛県 久万高原町,71.218254,73.529790,68.107833,-5.421957,11.336044,58.430729,0.000000,92.371911,58.218495,6.828160,68.239205,17.520028
1641,宮崎県 日之影町,71.213180,70.366260,63.395111,-6.971150,12.069810,58.875674,0.000000,92.956403,61.783431,4.029264,75.523049,11.612291

In [24]:
recommend_area_ml(
    data,
    urban=1.0,
    sightseeing=0.8,
    train_trip=0.6,
    ml_tourism=0.5,
    top_n=20
)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
631,東京都 豊島区,68.354470,94.759720,90.357779,-4.401941,87.040325,1.256182,0.000000,1.714226,0.159573,75.271087,5.669264,26.057621
624,東京都 品川区,66.282245,85.482055,91.331228,5.849173,80.128374,5.177418,5.007457,7.004974,0.994692,85.463277,8.053139,18.933195
619,東京都 新宿区,66.225917,94.901002,99.668078,4.767077,84.233339,3.252535,0.000000,4.507652,1.145125,67.752706,9.479467,21.670196
622,東京都 墨田区,65.272795,88.085439,96.042541,7.957102,82.729353,6.102775,0.000000,4.503391,0.642696,67.071512,11.282865,22.871969
621,東京都 台東区,65.215572,92.845517,96.315077,3.469560,83.081530,4.676194,0.000000,5.267706,0.824416,66.170925,11.862631,22.729419
620,東京都 文京区,64.818263,90.248617,93.245302,2.996685,85.245816,3.795310,0.000000,5.216957,1.375475,67.666603,8.660916,19.380667
629,東京都 中野区,64.151363,82.306517,87.837468,5.530951,84.121688,0.705612,0.000000,0.516878,0.369492,65.954137,2.437615,23.032562
633,東京都 荒川区,63.842233,78.721080,85.550002,6.828922,79.249681,4.299360,0.000000,3.576983,0.495341,75.081958,4.909424,22.585774
630,東京都 杉並区,63.616936,75.048266,82.510686,7.462419,83.625573,1.582599,0.000000,2.126077,1.062103,64.892072,5.830995,25.841194
625,東京都 目黒区,63.412393,81.973937,85.912216,3.938279,83.223185,0.813168,0.000000,1.058706,0.888461,62.034285,6.085769,25.620094
632,東京都 北区,63.176988,77.344658,83.633451,6.288793,78.614271,7.170789,0.000000,5.924585,1.087344,73.063529,6.334278,23.680187
617,東京都 中央区,62.831483,94.082960,90.845833,-3.237127,84.749800,8.872554,4.489272,8.200563,0.797346,61.717846,22.933012,18.759845
628,東京都 渋谷区,62.326148,94.268563,83.495754,-10.772809,79.892880,6.448476,0.000000,9.945034,3.581521,67.506310,8.105951,23.251608
627,東京都 世田谷区,61.961574,82.520544,84.410232,1.889688,80.413988,2.277217,0.000000,2.558809,1.480029,60.916358,6.570180,25.649557
618,東京都 港区,61.632581,94.964738,95.052661,0.087923,77.523811,6.493295,4.412439,8.985566,2.615644,65.922179,15.371849,17.663796
616,東京都 千代田区,61.288151,96.725265,90.328611,-6.396654,75.260121,14.759675,0.000000,20.337749,6.358621,70.165628,21.664262,19.014794
634,東京都 板橋区,60.140489,72.742394,79.443569,6.701175,79.846319,4.748756,0.000000,4.282796,1.502386,61.716704,7.596379,22.261616
635,東京都 練馬区,59.459907,75.538892,78.148879,2.609987,79.404660,2.240488,0.000000,3.114923,2.436746,56.848345,8.265734,24.807029
641,東京都 武蔵野市,59.342274,78.844490,76.684867,-2.159623,76.369572,2.168664,0.000000,3.290575,1.911392,58.259783,6.496057,28.030901
623,東京都 江東区,58.759803,93.189700,95.032030,1.842331,72.987731,9.508879,10.701955,10.337366,1.884141,60.535528,14.081741,16.972958

In [25]:
#区をなくす
data_no_ku = data[~data["地域"].str.endswith("区")].copy()

In [26]:
recommend_area_ml(
    data_no_ku,
    urban=1.0,
    sightseeing=0.8,
    train_trip=0.6,
    ml_tourism=0.5,
    top_n=20
)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
641,東京都 武蔵野市,59.342274,78.844490,76.684867,-2.159623,76.369572,2.168664,0.000000,3.290575,1.911392,58.259783,6.496057,28.030901
679,神奈川県 川崎市,58.195259,91.376604,94.629278,3.252675,71.588598,8.106835,6.188044,9.628527,4.473478,55.295058,11.789775,20.857473
1101,大阪府 大阪市,57.176180,97.310953,100.000000,2.689047,71.728679,7.458713,2.992677,6.648348,2.458827,49.684247,17.478614,17.839619
518,埼玉県 蕨市,56.511498,61.680421,73.786098,12.105677,77.546174,0.259846,0.000000,0.994944,2.515007,50.188537,11.762708,24.163748
1106,大阪府 吹田市,56.474788,82.760571,88.736459,5.975888,71.917950,8.250151,0.000000,12.035592,5.582625,52.297123,20.227644,20.140541
646,東京都 調布市,56.440863,78.008539,79.315517,1.306978,72.965655,7.045107,0.000000,7.021336,3.818078,52.691707,10.210011,24.300081
586,千葉県 浦安市,56.286136,91.373950,91.958478,0.584528,68.609380,6.766621,11.919997,8.432870,2.661598,41.661213,22.427893,29.555561
678,神奈川県 横浜市,56.137231,94.026897,93.735835,-0.291061,69.307319,10.434729,2.762077,13.113854,8.206345,49.775105,17.155889,20.947089
655,東京都 狛江市,55.509055,64.166688,66.567116,2.400429,75.488416,3.856030,0.000000,2.257912,2.135794,54.772833,7.069253,24.175733
564,千葉県 市川市,55.243596,76.941983,80.460259,3.518276,69.515601,10.365815,2.380854,8.816729,6.852105,53.217545,14.586093,23.162713
652,東京都 国分寺市,54.754349,63.520085,60.962099,-2.557986,73.317094,6.722712,0.000000,6.263210,6.267172,56.803554,7.846854,26.134170
653,東京都 国立市,54.722977,69.897193,75.448932,5.551739,72.248319,6.469681,0.000000,6.986653,5.193293,51.687788,17.231858,22.138970
644,東京都 府中市,53.784000,81.511846,81.788191,0.276345,68.878144,6.989198,0.000000,7.122943,3.981077,49.854585,13.541660,20.360762
575,千葉県 習志野市,53.711076,67.828610,75.550330,7.721720,70.083241,6.160543,3.253643,6.647426,5.952208,49.779536,22.037875,22.544992
664,東京都 西東京市,53.693424,67.703230,63.781295,-3.921935,74.756400,2.729010,0.000000,2.792552,3.551322,49.352659,9.947576,24.315359
648,東京都 小金井市,53.456008,65.393107,59.401297,-5.991810,73.212991,3.633777,0.000000,5.361722,3.133114,52.698323,6.836786,25.612237
568,千葉県 松戸市,53.129965,73.143448,71.929008,-1.214440,68.758972,8.181707,0.000000,7.244235,8.468006,50.395974,16.970612,23.894800
691,神奈川県 大和市,52.927553,66.640691,68.255346,1.614655,70.016109,6.319024,0.000000,8.304161,7.656636,49.552699,17.938966,24.518127
565,千葉県 船橋市,52.922347,72.588302,75.667655,3.079353,66.584276,11.330027,1.584913,10.705245,10.776318,51.317566,15.929918,22.832704
661,東京都 稲城市,52.319227,73.490449,77.158336,3.667888,61.930235,17.801662,0.000000,25.132098,10.957314,53.775442,14.796001,23.688864

In [27]:
#旅行タイプのリセット機能
travel_patterns_ml = {
    "海と自然でのんびり": {
        "sea": 1.0,
        "nature": 0.8,
        "ml_tourism": 0.6
    },
    "海沿い観光・リゾート": {
        "sea": 1.0,
        "sightseeing": 0.8,
        "ml_tourism": 0.7
    },
    "山と自然を楽しむ": {
        "mountain": 1.0,
        "nature": 1.0,
        "rural": 0.5,
        "ml_tourism": 0.6
    },
    "田舎でのんびり": {
        "rural": 1.0,
        "nature": 0.8,
        "car_trip": 0.6,
        "ml_tourism": 0.4
    },
    "都会で街歩き": {
        "urban": 1.0,
        "sightseeing": 0.8,
        "train_trip": 0.6,
        "ml_tourism": 0.5
    },
    "電車で行ける観光地": {
        "train_trip": 1.0,
        "sightseeing": 0.8,
        "urban": 0.4,
        "ml_tourism": 0.6
    }
}

In [28]:
#タイプ名で推薦する関数
def recommend_by_pattern_ml(data, pattern_name, top_n=20):
    if pattern_name not in travel_patterns_ml:
        raise ValueError(f"使える旅行タイプ: {list(travel_patterns_ml.keys())}")

    params = travel_patterns_ml[pattern_name]

    return recommend_area_ml(
        data,
        top_n=top_n,
        **params
    )

In [29]:
recommend_by_pattern_ml(data, "海と自然でのんびり", top_n=20)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
1715,沖縄県 座間味村,55.958239,59.620906,38.636424,-20.984483,15.646162,49.765015,71.305906,79.023367,34.783201,19.068919,35.183567,46.431111
677,東京都 小笠原村,53.561593,55.510956,29.703710,-25.807247,7.895623,50.906998,70.000000,83.506251,39.540315,14.819389,38.547114,32.110332
1714,沖縄県 渡嘉敷村,51.995438,53.467399,46.371149,-7.096251,16.956179,51.460065,55.798309,81.379837,40.513268,15.302928,47.738504,40.291104
1394,香川県 直島町,51.460717,67.364017,45.981705,-21.382312,22.905439,38.554626,65.072997,60.254601,31.486121,8.911615,45.414110,15.602115
1552,長崎県 小値賀町,51.059604,58.995489,48.841153,-10.154336,15.375095,45.923726,56.499377,61.463968,48.796648,9.301229,57.202855,25.468232
1717,沖縄県 渡名喜村,49.882809,37.500287,19.819627,-17.680660,16.044251,46.545180,70.590820,71.718261,36.971794,17.526315,38.631116,35.748825
1248,和歌山県 太地町,49.190147,70.299770,62.475672,-7.824097,27.819326,44.059684,45.323202,67.952244,43.599677,10.498559,64.026717,18.093428
1355,山口県 上関町,47.540241,67.651913,56.799773,-10.852140,14.532707,54.842662,36.142586,83.908547,51.706770,8.413006,61.832560,15.542171
1613,大分県 姫島村,46.754400,41.787991,42.734052,0.946061,20.069094,45.767200,49.956368,67.784787,37.126235,8.360846,38.719217,23.994002
251,宮城県 塩竈市,46.710836,0.000000,68.058153,68.058153,51.154719,16.086690,58.401762,25.094669,22.959432,25.183021,53.760720,16.829282
1411,愛媛県 上島町,46.139358,54.670969,46.877025,-7.793944,19.849816,47.298012,44.769835,62.442656,38.578599,9.447541,37.760819,13.811833
1554,長崎県 新上五島町,45.930509,71.947739,67.218629,-4.729110,18.078737,56.022858,25.083758,88.052145,51.445088,8.007830,65.462331,19.110419
428,茨城県 大洗町,45.835804,82.045700,82.294158,0.248459,29.711085,33.994164,33.434103,35.918497,37.647428,11.955601,64.274477,16.259979
1036,三重県 鳥羽市,44.639847,82.048718,80.243234,-1.805484,21.103392,53.757524,15.983673,82.447658,47.779130,12.470878,56.712844,29.347373
1286,島根県 海士町,44.589428,53.851730,51.021508,-2.830222,16.686147,53.509237,33.594332,82.613285,50.956442,8.605962,63.643947,16.608608
1720,沖縄県 伊平屋村,44.185724,49.791419,42.668484,-7.122935,12.192286,50.362620,40.154552,69.924662,55.182577,5.535354,71.718868,18.812190
1039,三重県 志摩市,44.177787,79.422205,76.696093,-2.726112,22.833948,48.670148,21.072914,72.399656,48.606163,9.224435,67.371190,21.977681
1251,和歌山県 串本町,44.003953,75.615313,73.781768,-1.833545,21.480280,54.555990,17.695634,84.356922,49.761061,10.036884,64.465718,21.858018
671,東京都 新島村,43.951925,50.240273,41.361351,-8.878922,16.608512,49.993837,40.672739,80.153941,44.663619,11.236348,59.991405,26.527449
1238,和歌山県 美浜町,43.885118,57.896778,54.020166,-3.876612,26.680061,43.661463,37.983012,58.865623,43.369942,9.401344,61.436149,13.119281

In [30]:
recommend_by_pattern_ml(data_no_ku, "都会で街歩き", top_n=20)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
641,東京都 武蔵野市,59.342274,78.844490,76.684867,-2.159623,76.369572,2.168664,0.000000,3.290575,1.911392,58.259783,6.496057,28.030901
679,神奈川県 川崎市,58.195259,91.376604,94.629278,3.252675,71.588598,8.106835,6.188044,9.628527,4.473478,55.295058,11.789775,20.857473
1101,大阪府 大阪市,57.176180,97.310953,100.000000,2.689047,71.728679,7.458713,2.992677,6.648348,2.458827,49.684247,17.478614,17.839619
518,埼玉県 蕨市,56.511498,61.680421,73.786098,12.105677,77.546174,0.259846,0.000000,0.994944,2.515007,50.188537,11.762708,24.163748
1106,大阪府 吹田市,56.474788,82.760571,88.736459,5.975888,71.917950,8.250151,0.000000,12.035592,5.582625,52.297123,20.227644,20.140541
646,東京都 調布市,56.440863,78.008539,79.315517,1.306978,72.965655,7.045107,0.000000,7.021336,3.818078,52.691707,10.210011,24.300081
586,千葉県 浦安市,56.286136,91.373950,91.958478,0.584528,68.609380,6.766621,11.919997,8.432870,2.661598,41.661213,22.427893,29.555561
678,神奈川県 横浜市,56.137231,94.026897,93.735835,-0.291061,69.307319,10.434729,2.762077,13.113854,8.206345,49.775105,17.155889,20.947089
655,東京都 狛江市,55.509055,64.166688,66.567116,2.400429,75.488416,3.856030,0.000000,2.257912,2.135794,54.772833,7.069253,24.175733
564,千葉県 市川市,55.243596,76.941983,80.460259,3.518276,69.515601,10.365815,2.380854,8.816729,6.852105,53.217545,14.586093,23.162713
652,東京都 国分寺市,54.754349,63.520085,60.962099,-2.557986,73.317094,6.722712,0.000000,6.263210,6.267172,56.803554,7.846854,26.134170
653,東京都 国立市,54.722977,69.897193,75.448932,5.551739,72.248319,6.469681,0.000000,6.986653,5.193293,51.687788,17.231858,22.138970
644,東京都 府中市,53.784000,81.511846,81.788191,0.276345,68.878144,6.989198,0.000000,7.122943,3.981077,49.854585,13.541660,20.360762
575,千葉県 習志野市,53.711076,67.828610,75.550330,7.721720,70.083241,6.160543,3.253643,6.647426,5.952208,49.779536,22.037875,22.544992
664,東京都 西東京市,53.693424,67.703230,63.781295,-3.921935,74.756400,2.729010,0.000000,2.792552,3.551322,49.352659,9.947576,24.315359
648,東京都 小金井市,53.456008,65.393107,59.401297,-5.991810,73.212991,3.633777,0.000000,5.361722,3.133114,52.698323,6.836786,25.612237
568,千葉県 松戸市,53.129965,73.143448,71.929008,-1.214440,68.758972,8.181707,0.000000,7.244235,8.468006,50.395974,16.970612,23.894800
691,神奈川県 大和市,52.927553,66.640691,68.255346,1.614655,70.016109,6.319024,0.000000,8.304161,7.656636,49.552699,17.938966,24.518127
565,千葉県 船橋市,52.922347,72.588302,75.667655,3.079353,66.584276,11.330027,1.584913,10.705245,10.776318,51.317566,15.929918,22.832704
661,東京都 稲城市,52.319227,73.490449,77.158336,3.667888,61.930235,17.801662,0.000000,25.132098,10.957314,53.775442,14.796001,23.688864

In [31]:
#観光ポテンシャル差ランキング（観光地としての特徴はあるが観光客が少ない）
data[[
    "地域",
    "観光人気度",
    "ML観光ポテンシャル",
    "観光ポテンシャル差",
    "都会度",
    "自然度",
    "海度",
    "山っぽさ",
    "田舎度",
    "観光・街歩き向き"
]].sort_values(
    "観光ポテンシャル差",
    ascending=False
).head(30)

,地域,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,観光・街歩き向き
251,宮城県 塩竈市,0.000000,68.058153,68.058153,51.154719,16.086690,58.401762,25.094669,22.959432,16.829282
51,北海道 今金町,0.000000,62.206893,62.206893,6.753773,56.218200,0.000000,85.229302,55.788292,21.118370
123,北海道 訓子府町,0.000000,57.715861,57.715861,8.355039,52.096879,0.000000,63.379717,61.321630,11.662414
109,北海道 猿払村,0.000000,49.308559,49.308559,3.657830,51.951353,1.946474,80.009851,54.815359,9.974045
1117,大阪府 河内長野市,0.000000,34.508063,34.508063,38.069310,49.524705,0.000000,74.185791,36.006071,19.942288
401,茨城県 龍ケ崎市,0.000000,33.164819,33.164819,33.742727,32.803724,0.000000,26.287036,35.592322,17.410833
1288,島根県 知夫村,21.100116,53.899166,32.799050,14.687577,51.379401,26.958695,82.266521,48.506547,19.693587
588,千葉県 袖ケ浦市,0.000000,29.898211,29.898211,32.327999,32.923261,1.920391,35.117093,36.796225,11.283364
583,千葉県 鎌ケ谷市,0.000000,26.295818,26.295818,60.987430,13.012962,0.000000,12.019381,14.549123,24.103919
236,岩手県 金ケ崎町,0.000000,26.072396,26.072396,14.563535,50.296200,0.000000,62.016848,54.515972,6.782429
921,岐阜県 関ケ原町,0.000000,24.821699,24.821699,24.066458,53.640348,0.000000,81.214629,48.126566,10.691475
1707,沖縄県 嘉手納町,48.690441,71.986278,23.295836,28.231165,26.388662,0.000000,39.464415,30.145285,16.126970
1447,高知県 檮原町,0.000000,20.023806,20.023806,12.515639,59.291339,0.000000,93.584550,56.155792,17.786228
1488,福岡県 久山町,56.746178,74.360817,17.614638,24.393516,49.592679,0.000000,73.979865,44.437424,9.974477
71,北海道 上砂川町,0.000000,17.605082,17.605082,19.634925,56.401910,0.000000,89.325191,49.931860,9.767757
303,秋田県 八郎潟町,46.298671,63.858737,17.560065,23.101634,41.661651,0.000000,37.919771,47.050897,15.156465
1592,熊本県 湯前町,53.224002,69.715368,16.491365,16.835093,54.156411,0.000000,78.508040,57.853049,16.451733
599,千葉県 酒々井町,52.888444,67.348704,14.460260,41.170249,32.412798,0.000000,35.847110,32.608898,29.839149
68,北海道 古平町,0.000000,14.339482,14.339482,10.908806,58.809420,0.582596,93.911388,50.859426,14.905580
199,青森県 野辺地町,58.552910,71.878594,13.325683,20.473358,52.245816,2.483988,76.694931,48.343329,19.991233
45,北海道 長万部町,23.991851,37.280327,13.288475,9.235689,54.245869,4.417708,83.258568,52.396717,16.670844
1210,奈良県 河合町,51.142252,64.380589,13.238337,49.932156,21.871529,0.000000,21.571938,22.478881,24.704022
1331,広島県 府中町,55.140010,68.172857,13.032847,48.203245,30.092928,0.000000,45.462783,22.575526,16.084477
239,岩手県 大槌町,57.608685,70.349520,12.740835,18.209908,58.207801,1.331065,90.474343,53.251162,16.875075
1083,京都府 向日市,55.916283,68.533853,12.617570,62.487483,13.761728,0.000000,16.645360,12.295885,21.360344
322,山形県 山辺町,57.436161,69.998198,12.562037,21.453972,50.322177,0.000000,65.659646,51.641757,15.498716
1332,広島県 海田町,52.006940,64.205285,12.198345,40.563826,38.876916,0.000000,58.497151,29.110715,16.855495
518,埼玉県 蕨市,61.680421,73.786098,12.105677,77.546174,0.259846,0.000000,0.994944,2.515007,24.163748
168,北海道 標茶町,51.049667,62.673050,11.623383,3.982009,50.048059,0.000000,67.501655,57.022229,21.195127
842,長野県 北相木村,0.000000,11.531709,11.531709,13.201221,59.446200,0.000000,92.924498,57.266492,14.980960

In [32]:
data.to_csv(
    "~/Desktop/趣味/travel_recommendation_data_ml.csv",
    index=False,
    encoding="utf-8-sig"
)

print("保存しました")

保存しました

In [33]:
data = pd.read_csv("~/Desktop/趣味/travel_recommendation_data_ml.csv")

In [34]:
recommend_area_ml(
    data,
    sea=1.0,
    nature=0.8,
    ml_tourism=0.6,
    top_n=20
)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
1715,沖縄県 座間味村,55.958239,59.620906,38.636424,-20.984483,15.646162,49.765015,71.305906,79.023367,34.783201,19.068919,35.183567,46.431111
677,東京都 小笠原村,53.561593,55.510956,29.703710,-25.807247,7.895623,50.906998,70.000000,83.506251,39.540315,14.819389,38.547114,32.110332
1714,沖縄県 渡嘉敷村,51.995438,53.467399,46.371149,-7.096251,16.956179,51.460065,55.798309,81.379837,40.513268,15.302928,47.738504,40.291104
1394,香川県 直島町,51.460717,67.364017,45.981705,-21.382312,22.905439,38.554626,65.072997,60.254601,31.486121,8.911615,45.414110,15.602115
1552,長崎県 小値賀町,51.059604,58.995489,48.841153,-10.154336,15.375095,45.923726,56.499377,61.463968,48.796648,9.301229,57.202855,25.468232
1717,沖縄県 渡名喜村,49.882809,37.500287,19.819627,-17.680660,16.044251,46.545180,70.590820,71.718261,36.971794,17.526315,38.631116,35.748825
1248,和歌山県 太地町,49.190147,70.299770,62.475672,-7.824097,27.819326,44.059684,45.323202,67.952244,43.599677,10.498559,64.026717,18.093428
1355,山口県 上関町,47.540241,67.651913,56.799773,-10.852140,14.532707,54.842662,36.142586,83.908547,51.706770,8.413006,61.832560,15.542171
1613,大分県 姫島村,46.754400,41.787991,42.734052,0.946061,20.069094,45.767200,49.956368,67.784787,37.126235,8.360846,38.719217,23.994002
251,宮城県 塩竈市,46.710836,0.000000,68.058153,68.058153,51.154719,16.086690,58.401762,25.094669,22.959432,25.183021,53.760720,16.829282
1411,愛媛県 上島町,46.139358,54.670969,46.877025,-7.793944,19.849816,47.298012,44.769835,62.442656,38.578599,9.447541,37.760819,13.811833
1554,長崎県 新上五島町,45.930509,71.947739,67.218629,-4.729110,18.078737,56.022858,25.083758,88.052145,51.445088,8.007830,65.462331,19.110419
428,茨城県 大洗町,45.835804,82.045700,82.294158,0.248459,29.711085,33.994164,33.434103,35.918497,37.647428,11.955601,64.274477,16.259979
1036,三重県 鳥羽市,44.639847,82.048718,80.243234,-1.805484,21.103392,53.757524,15.983673,82.447658,47.779130,12.470878,56.712844,29.347373
1286,島根県 海士町,44.589428,53.851730,51.021508,-2.830222,16.686147,53.509237,33.594332,82.613285,50.956442,8.605962,63.643947,16.608608
1720,沖縄県 伊平屋村,44.185724,49.791419,42.668484,-7.122935,12.192286,50.362620,40.154552,69.924662,55.182577,5.535354,71.718868,18.812190
1039,三重県 志摩市,44.177787,79.422205,76.696093,-2.726112,22.833948,48.670148,21.072914,72.399656,48.606163,9.224435,67.371190,21.977681
1251,和歌山県 串本町,44.003953,75.615313,73.781768,-1.833545,21.480280,54.555990,17.695634,84.356922,49.761061,10.036884,64.465718,21.858018
671,東京都 新島村,43.951925,50.240273,41.361351,-8.878922,16.608512,49.993837,40.672739,80.153941,44.663619,11.236348,59.991405,26.527449
1238,和歌山県 美浜町,43.885118,57.896778,54.020166,-3.876612,26.680061,43.661463,37.983012,58.865623,43.369942,9.401344,61.436149,13.119281

In [35]:
travel_patterns_ml = {
    "海と自然でのんびり": {
        "sea": 1.0,
        "nature": 0.8,
        "ml_tourism": 0.6
    },
    "海沿い観光・リゾート": {
        "sea": 1.0,
        "sightseeing": 0.8,
        "ml_tourism": 0.7
    },
    "山と自然を楽しむ": {
        "mountain": 1.0,
        "nature": 1.0,
        "rural": 0.5,
        "ml_tourism": 0.6
    },
    "田舎でのんびり": {
        "rural": 1.0,
        "nature": 0.8,
        "car_trip": 0.6,
        "ml_tourism": 0.4
    },
    "都会で街歩き": {
        "urban": 1.0,
        "sightseeing": 0.8,
        "train_trip": 0.6,
        "ml_tourism": 0.5
    },
    "電車で行ける観光地": {
        "train_trip": 1.0,
        "sightseeing": 0.8,
        "urban": 0.4,
        "ml_tourism": 0.6
    }
}

In [36]:
def recommend_by_pattern_ml(data, pattern_name, top_n=20):
    if pattern_name not in travel_patterns_ml:
        raise ValueError(f"使える旅行タイプ: {list(travel_patterns_ml.keys())}")

    params = travel_patterns_ml[pattern_name]

    return recommend_area_ml(
        data,
        top_n=top_n,
        **params
    )

In [37]:
recommend_by_pattern_ml(data, "海と自然でのんびり", top_n=5)

,地域,おすすめスコア,観光人気度,ML観光ポテンシャル,観光ポテンシャル差,都会度,自然度,海度,山っぽさ,田舎度,電車旅向き,車旅向き,観光・街歩き向き
1715,沖縄県 座間味村,55.958239,59.620906,38.636424,-20.984483,15.646162,49.765015,71.305906,79.023367,34.783201,19.068919,35.183567,46.431111
677,東京都 小笠原村,53.561593,55.510956,29.703710,-25.807247,7.895623,50.906998,70.000000,83.506251,39.540315,14.819389,38.547114,32.110332
1714,沖縄県 渡嘉敷村,51.995438,53.467399,46.371149,-7.096251,16.956179,51.460065,55.798309,81.379837,40.513268,15.302928,47.738504,40.291104
1394,香川県 直島町,51.460717,67.364017,45.981705,-21.382312,22.905439,38.554626,65.072997,60.254601,31.486121,8.911615,45.414110,15.602115
1552,長崎県 小値賀町,51.059604,58.995489,48.841153,-10.154336,15.375095,45.923726,56.499377,61.463968,48.796648,9.301229,57.202855,25.468232

In [38]:
#簡易診断
def travel_diagnosis_ml(data, top_n=10):
    print("旅行タイプを選んでください")
    print("====================")

    pattern_names = list(travel_patterns_ml.keys())

    for i, name in enumerate(pattern_names, start=1):
        print(f"{i}. {name}")

    choice = int(input("番号を入力してください: "))

    if choice < 1 or choice > len(pattern_names):
        print("正しい番号を入力してください")
        return None

    selected_pattern = pattern_names[choice - 1]

    print(f"\n選択した旅行タイプ: {selected_pattern}")
    print("====================")

    return recommend_by_pattern_ml(data, selected_pattern, top_n=top_n)